server:
  port: 15600
spring:
  batch:
    initialize-schema: embedded
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/postgres_real_1?ApplicationName=Prevision-Batch
    username: postgres
    password: 123qwer@
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 400
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 1000
        show_sql: false
        use_sql_comments: true
logging:
  file:
    path: D:/_PDS_LOG
  level:
    com: info
    org: error
application:
  title: Batch
  version: 1.5.1

pvBatch:
  page_size: 100
  chunk_size: 100
  schedule_pool_size: 2           # schedule thread pool 갯수
  restart_interval_seconds: 60000 # 배치 schedule 완료 후 재시작 사이의 시간 간격 ( milliseconds )
  parallel_interval_seconds: 100  # 병렬 job 들 사이의 시간 간격 ( milliseconds )
  execute_type: J # S = step | J = job

